apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web
  name: tripviewer
  labels:
    app: tripviewer
spec:
  selector:
    matchLabels:
      app: tripviewer
  replicas: 1
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - image: "registrygwq5120.azurecr.io/tripviewer:1.1"
        name: tripviewer-image
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        env:
        - name: "TRIPS_API_ENDPOINT"
          value: "http://trips-service/api/trips"
        - name: "USERPROFILE_API_ENDPOINT"
          value: "http://userprofile-service/api/user"
---

apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
spec:
  selector:
    app: tripviewer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tripviewer-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: tripviewer-service
            port:
              number: 80
