kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-access
subjects:
- kind: Group
  namespace: web
  name: 929adab5-fcaf-4a4f-8eda-0b9acd33848f