apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  labels:
    app: user-java
spec:
  selector:
    matchLabels:
      app: user-java
  replicas: 2
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - image: "registrygwq5120.azurecr.io/user-java:1.0"
        name: user-java-image
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
---

apiVersion: v1
kind: Service
metadata:
  name: user-java-service
spec:
  selector:
    app: user-java
  ports:
  - name: user-java-service
    protocol: TCP
    port: 80
    targetPort: 80
