apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: api
  name: trips
  labels:
    app: trips
spec:
  selector:
    matchLabels:
      app: trips
  replicas: 1
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - image: "registrygwq5120.azurecr.io/trips:1.0"
        name: trips-image
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
---

apiVersion: v1
kind: Service
metadata:
  name: trips-service
spec:
  selector:
    app: trips
  ports:
  - name: trips-service
    protocol: TCP
    port: 80
    targetPort: 80