apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: api
  name: poi
  labels:
    app: poi
spec:
  selector:
    matchLabels:
      app: poi
  replicas: 1
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - image: "registrygwq5120.azurecr.io/poi:1.1"
        name: poi-image
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        env:
        - name: "SQL_SERVER"
          value: "sqlservergwq5120.database.windows.net"
        - name: "SQL_USER"
          value: "sqladmingWq5120"
        - name: "SQL_DB_NAME"
          value: "mydrivingDB"
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Production"
        - name: "CONFIG_FILES_PATH"
          value: "/secrets"
        - name: "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT"
          value: "false"
        - name: "WEB_SERVER_BASE_URI"
          value: "http://0.0.0.0"
        - name: "WEB_PORT"
          value: "80"
        - name: "SQL_PASSWORD"
          valueFrom:
            secretKeyRef:
             name: sql-password
             key: sql-password

---

apiVersion: v1
kind: Service
metadata:
  name: poi-service
spec:
  selector:
    app: poi
  ports:
  - name: poi-service 
    protocol: TCP
    port: 80
    targetPort: 80
